samples/cxl_hello_fpga/cxl_hello_fpga.cpp
NAME
samples/cxl_hello_fpga/cxl_hello_fpga.cpp
SYNOPSIS
#include 'cxl_hello_fpga.h'
#include <signal.h>
#include <CLI/CLI.hpp>
#include <iostream>
#include 'cxl_hello_fpga_cmd.h'
Functions
void he_sig_handler (int)
int main (int argc, char *argv[])
Function Documentation
void he_sig_handler (int)
Definition at line 36 of file cxl_hello_fpga_cmd.h.
References g_he_exit.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 37 of file cxl_hello_fpga.cpp.
References app, he_sig_handler(), opae::afu_test::afu::main(), and opae::afu_test::afu::register_command().
Author
Generated automatically by Doxygen for OPAE C API from the source code.