.TH "samples/cxl_hello_fpga/cxl_hello_fpga.cpp" 3 "Mon Feb 12 2024" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
samples/cxl_hello_fpga/cxl_hello_fpga.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'cxl_hello_fpga\&.h'\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include <CLI/CLI\&.hpp>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'cxl_hello_fpga_cmd\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBhe_sig_handler\fP (int)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void he_sig_handler (int)"

.PP
Definition at line 36 of file cxl_hello_fpga_cmd\&.h\&.
.PP
References g_he_exit\&.
.PP
Referenced by main()\&.
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 37 of file cxl_hello_fpga\&.cpp\&.
.PP
References app, he_sig_handler(), opae::afu_test::afu::main(), and opae::afu_test::afu::register_command()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
