hello_fpga::he_cmd
NAME
hello_fpga::he_cmd
SYNOPSIS
#include </root/samples/cxl_hello_fpga/cxl_he_cmd.h>
Inherits opae::afu_test::command.
Inherited by hello_fpga::he_cache_cmd.
Public Member Functions
he_cmd ()
virtual ~he_cmd ()
double he_num_xfers_to_bw (uint64_t num_lines, uint64_t num_ticks)
void he_perf_counters (he_cxl_latency cxl_latency=HE_CXL_LATENCY_NONE)
void print_csr ()
void host_exerciser_errors ()
int parse_input_options ()
bool he_wait_test_completion (const char *str='Test started ......')
bool he_set_bias_mode ()
void he_start_test ()
bool verify_numa_node ()
Protected Attributes
hello_fpga * host_exe_
uint32_t he_clock_mhz_
uint32_t numa_node_
uint32_t he_target_
uint32_t he_bias_
he_ctl he_ctl_
he_info he_info_
he_rd_config he_rd_cfg_
he_wr_config he_wr_cfg_
he_rd_addr_table_ctrl rd_table_ctl_
he_wr_addr_table_ctrl wr_table_ctl_
Additional Inherited Members
Detailed Description
Definition at line 40 of file cxl_he_cmd.h.
Constructor & Destructor Documentation
hello_fpga::he_cmd::he_cmd () [inline]
Definition at line 42 of file cxl_he_cmd.h.
References he_ctl_, he_info_, he_rd_cfg_, he_wr_cfg_, rd_table_ctl_, hello_fpga::he_ctl::value, hello_fpga::he_info::value, hello_fpga::he_wr_config::value, hello_fpga::he_wr_addr_table_ctrl::value, hello_fpga::he_rd_config::value, hello_fpga::he_rd_addr_table_ctrl::value, and wr_table_ctl_.
virtual hello_fpga::he_cmd::~he_cmd () [inline], [virtual]
Definition at line 56 of file cxl_he_cmd.h.
Member Function Documentation
double hello_fpga::he_cmd::he_num_xfers_to_bw (uint64_t num_lines, uint64_t num_ticks) [inline]
Definition at line 59 of file cxl_he_cmd.h.
References he_clock_mhz_.
Referenced by he_perf_counters().
void hello_fpga::he_cmd::he_perf_counters (he_cxl_latency cxl_latency = HE_CXL_LATENCY_NONE) [inline]
Definition at line 63 of file cxl_he_cmd.h.
References hello_fpga::he_cache_dsm_status::actual_data, hello_fpga::he_cache_dsm_status::dsm_number, hello_fpga::he_cache_dsm_status::err_vector, hello_fpga::he_cache_dsm_status::expected_data, opae::afu_test::afu::get_dsm(), hello_fpga::HE_CXL_RD_LATENCY, he_num_xfers_to_bw(), host_exe_, opae::afu_test::afu::logger_, hello_fpga::he_cache_dsm_status::num_reads, hello_fpga::he_cache_dsm_status::num_ticks, hello_fpga::he_cache_dsm_status::num_writes, hello_fpga::he_cache_dsm_status::penalty_end, hello_fpga::he_cache_dsm_status::penalty_start, and hello_fpga::he_cache_dsm_status::test_completed.
Referenced by hello_fpga::he_cache_cmd::he_run_hello_fpga_test().
void hello_fpga::he_cmd::print_csr () [inline]
Definition at line 106 of file cxl_he_cmd.h.
References hello_fpga::HE_CTL, hello_fpga::HE_DFH, hello_fpga::HE_DSM_BASE, hello_fpga::HE_ERROR_ACT_DATA0, hello_fpga::HE_ERROR_ACT_DATA1, hello_fpga::HE_ERROR_ACT_DATA2, hello_fpga::HE_ERROR_ACT_DATA3, hello_fpga::HE_ERROR_ACT_DATA4, hello_fpga::HE_ERROR_ACT_DATA5, hello_fpga::HE_ERROR_ACT_DATA6, hello_fpga::HE_ERROR_ACT_DATA7, hello_fpga::HE_ERROR_EXP_DATA, hello_fpga::HE_ERROR_STATUS, hello_fpga::HE_ID_H, hello_fpga::HE_ID_L, hello_fpga::HE_INFO, hello_fpga::HE_RD_ADDR_TABLE_CTRL, hello_fpga::HE_RD_ADDR_TABLE_DATA, hello_fpga::HE_RD_CONFIG, hello_fpga::HE_RD_NUM_LINES, hello_fpga::HE_SCRATCHPAD0, hello_fpga::HE_WR_ADDR_TABLE_CTRL, hello_fpga::HE_WR_ADDR_TABLE_DATA, hello_fpga::HE_WR_BYTE_ENABLE, hello_fpga::HE_WR_CONFIG, hello_fpga::HE_WR_NUM_LINES, host_exe_, opae::afu_test::afu::logger_, and opae::afu_test::afu::read64().
Referenced by hello_fpga::he_cache_cmd::run().
void hello_fpga::he_cmd::host_exerciser_errors () [inline]
Definition at line 179 of file cxl_he_cmd.h.
References hello_fpga::HE_ERROR_ACT_DATA0, hello_fpga::HE_ERROR_ACT_DATA1, hello_fpga::HE_ERROR_ACT_DATA2, hello_fpga::HE_ERROR_ACT_DATA3, hello_fpga::HE_ERROR_ACT_DATA4, hello_fpga::HE_ERROR_ACT_DATA5, hello_fpga::HE_ERROR_ACT_DATA6, hello_fpga::HE_ERROR_ACT_DATA7, hello_fpga::HE_ERROR_EXP_DATA, hello_fpga::HE_ERROR_STATUS, host_exe_, opae::afu_test::afu::read64(), and hello_fpga::he_err_status::value.
Referenced by hello_fpga::he_cache_cmd::he_run_hello_fpga_test().
int hello_fpga::he_cmd::parse_input_options () [inline]
Definition at line 222 of file cxl_he_cmd.h.
References host_exe_.
bool hello_fpga::he_cmd::he_wait_test_completion (const char * str = 'Test started ......') [inline]
Definition at line 228 of file cxl_he_cmd.h.
References opae::afu_test::afu::get_dsm(), hello_fpga::HE_CACHE_TEST_SLEEP_INVL, hello_fpga::HE_CACHE_TEST_TIMEOUT, host_exe_, and usleep().
Referenced by hello_fpga::he_cache_cmd::he_run_hello_fpga_test().
bool hello_fpga::he_cmd::he_set_bias_mode () [inline]
Definition at line 244 of file cxl_he_cmd.h.
References hello_fpga::FPGAMEM_DEVICE_BIAS, hello_fpga::FPGAMEM_HOST_BIAS, he_bias_, he_ctl_, he_target_, hello_fpga::HE_TARGET_HOST, and hello_fpga::HOSTMEM_BIAS.
void hello_fpga::he_cmd::he_start_test () [inline]
Definition at line 267 of file cxl_he_cmd.h.
References hello_fpga::HE_CTL, he_ctl_, host_exe_, hello_fpga::he_ctl::value, and opae::afu_test::afu::write64().
Referenced by hello_fpga::he_cache_cmd::he_run_hello_fpga_test().
bool hello_fpga::he_cmd::verify_numa_node () [inline]
Definition at line 275 of file cxl_he_cmd.h.
References he_target_, hello_fpga::HE_TARGET_HOST, and numa_node_.
Referenced by hello_fpga::he_cache_cmd::run().
Field Documentation
hello_fpga* hello_fpga::he_cmd::host_exe_ [protected]
Definition at line 300 of file cxl_he_cmd.h.
Referenced by he_perf_counters(), hello_fpga::he_cache_cmd::he_run_hello_fpga_test(), he_start_test(), he_wait_test_completion(), hello_fpga::he_cache_cmd::hello_fpga_data_intg_check(), host_exerciser_errors(), parse_input_options(), print_csr(), and hello_fpga::he_cache_cmd::run().
uint32_t hello_fpga::he_cmd::he_clock_mhz_ [protected]
Definition at line 301 of file cxl_he_cmd.h.
Referenced by he_num_xfers_to_bw().
uint32_t hello_fpga::he_cmd::numa_node_ [protected]
Definition at line 302 of file cxl_he_cmd.h.
Referenced by hello_fpga::he_cache_cmd::he_run_hello_fpga_test(), hello_fpga::he_cache_cmd::run(), and verify_numa_node().
uint32_t hello_fpga::he_cmd::he_target_ [protected]
Definition at line 303 of file cxl_he_cmd.h.
Referenced by he_set_bias_mode(), and verify_numa_node().
uint32_t hello_fpga::he_cmd::he_bias_ [protected]
Definition at line 304 of file cxl_he_cmd.h.
Referenced by he_set_bias_mode().
he_ctl hello_fpga::he_cmd::he_ctl_ [protected]
Definition at line 306 of file cxl_he_cmd.h.
Referenced by he_cmd(), he_set_bias_mode(), he_start_test(), and hello_fpga::he_cache_cmd::run().
he_info hello_fpga::he_cmd::he_info_ [protected]
Definition at line 307 of file cxl_he_cmd.h.
Referenced by he_cmd(), and hello_fpga::he_cache_cmd::he_run_hello_fpga_test().
he_rd_config hello_fpga::he_cmd::he_rd_cfg_ [protected]
Definition at line 308 of file cxl_he_cmd.h.
Referenced by he_cmd().
he_wr_config hello_fpga::he_cmd::he_wr_cfg_ [protected]
Definition at line 309 of file cxl_he_cmd.h.
Referenced by he_cmd(), and hello_fpga::he_cache_cmd::he_run_hello_fpga_test().
he_rd_addr_table_ctrl hello_fpga::he_cmd::rd_table_ctl_ [protected]
Definition at line 310 of file cxl_he_cmd.h.
Referenced by he_cmd().
he_wr_addr_table_ctrl hello_fpga::he_cmd::wr_table_ctl_ [protected]
Definition at line 311 of file cxl_he_cmd.h.
Referenced by he_cmd(), and hello_fpga::he_cache_cmd::he_run_hello_fpga_test().
Author
Generated automatically by Doxygen for OPAE C API from the source code.