.TH "hello_fpga::he_rd_num_lines" 3 "Mon Feb 12 2024" "Version -.." "OPAE C API" \" -*- nroff -*-
.ad l
.nh
.SH NAME
hello_fpga::he_rd_num_lines
.SH SYNOPSIS
.br
.PP
.PP
\fC#include </root/samples/cxl_hello_fpga/cxl_hello_fpga\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBoffset\fP = HE_RD_NUM_LINES }"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint64_t \fBvalue\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "uint64_t \fBread_num_lines\fP: 16"
.br
.ti -1c
.RI "uint64_t \fBreserved\fP: 48"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 206 of file cxl_hello_fpga\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIoffset \fP\fP
.PP
Definition at line 207 of file cxl_hello_fpga\&.h\&.
.SH "Field Documentation"
.PP 
.SS "uint64_t hello_fpga::he_rd_num_lines::value"

.PP
Definition at line 208 of file cxl_hello_fpga\&.h\&.
.SS "struct { \&.\&.\&. } "


.SH "Author"
.PP 
Generated automatically by Doxygen for OPAE C API from the source code\&.
