hello_fpga::he_cache_cmd
NAME
hello_fpga::he_cache_cmd
SYNOPSIS
#include </root/samples/cxl_hello_fpga/cxl_hello_fpga_cmd.h>
Inherits hello_fpga::he_cmd.
Public Member Functions
he_cache_cmd ()
virtual ~he_cache_cmd ()
virtual const char * name () const override
virtual const char * description () const override
virtual const char * afu_id () const override
virtual uint64_t featureid () const override
virtual uint64_t guidl () const override
virtual uint64_t guidh () const override
virtual void add_options (CLI::App *app) override
bool hello_fpga_data_intg_check (uint8_t *buf_address)
int he_run_hello_fpga_test ()
virtual int run (test_afu *afu, CLI::App *app)
Protected Attributes
uint32_t he_test_
Additional Inherited Members
Detailed Description
Definition at line 43 of file cxl_hello_fpga_cmd.h.
Constructor & Destructor Documentation
hello_fpga::he_cache_cmd::he_cache_cmd () [inline]
Definition at line 45 of file cxl_hello_fpga_cmd.h.
virtual hello_fpga::he_cache_cmd::~he_cache_cmd () [inline], [virtual]
Definition at line 47 of file cxl_hello_fpga_cmd.h.
Member Function Documentation
virtual const char* hello_fpga::he_cache_cmd::name () const [inline], [override], [virtual]
Implements opae::afu_test::command.
Definition at line 49 of file cxl_hello_fpga_cmd.h.
virtual const char* hello_fpga::he_cache_cmd::description () const [inline], [override], [virtual]
Implements opae::afu_test::command.
Definition at line 51 of file cxl_hello_fpga_cmd.h.
virtual const char* hello_fpga::he_cache_cmd::afu_id () const [inline], [override], [virtual]
Reimplemented from opae::afu_test::command.
Definition at line 55 of file cxl_hello_fpga_cmd.h.
References HE_CACHE_AFU_ID.
virtual uint64_t hello_fpga::he_cache_cmd::featureid () const [inline], [override], [virtual]
Implements opae::afu_test::command.
Definition at line 57 of file cxl_hello_fpga_cmd.h.
References MEM_TG_FEATURE_ID.
virtual uint64_t hello_fpga::he_cache_cmd::guidl () const [inline], [override], [virtual]
Implements opae::afu_test::command.
Definition at line 59 of file cxl_hello_fpga_cmd.h.
References MEM_TG_FEATURE_GUIDL.
virtual uint64_t hello_fpga::he_cache_cmd::guidh () const [inline], [override], [virtual]
Implements opae::afu_test::command.
Definition at line 61 of file cxl_hello_fpga_cmd.h.
References MEM_TG_FEATURE_GUIDH.
virtual void hello_fpga::he_cache_cmd::add_options (CLI::App * app) [inline], [override], [virtual]
Reimplemented from opae::afu_test::command.
Definition at line 63 of file cxl_hello_fpga_cmd.h.
References app, and hello_fpga::he_test_modes.
bool hello_fpga::he_cache_cmd::hello_fpga_data_intg_check (uint8_t * buf_address) [inline]
Definition at line 70 of file cxl_hello_fpga_cmd.h.
References hello_fpga::CL, opae::afu_test::afu::free_cache_read_write(), opae::afu_test::afu::free_dsm(), opae::afu_test::afu::get_write_buff_phy_addr(), HELLO_FPGA_CL_HEADER, hello_fpga::HELLO_FPGA_NUMCACHE_LINES, and hello_fpga::he_cmd::host_exe_.
Referenced by he_run_hello_fpga_test().
int hello_fpga::he_cache_cmd::he_run_hello_fpga_test () [inline]
Definition at line 142 of file cxl_hello_fpga_cmd.h.
References opae::afu_test::afu::allocate_cache_read_write(), opae::afu_test::afu::allocate_dsm(), hello_fpga::BUFFER_SIZE_2MB, opae::afu_test::afu::free_cache_read_write(), opae::afu_test::afu::free_dsm(), opae::afu_test::afu::get_read_write(), hello_fpga::HE_INFO, hello_fpga::he_cmd::he_info_, hello_fpga::he_cmd::he_perf_counters(), hello_fpga::he_cmd::he_start_test(), hello_fpga::he_cmd::he_wait_test_completion(), hello_fpga::HE_WR_ADDR_TABLE_CTRL, hello_fpga::he_cmd::he_wr_cfg_, hello_fpga::HE_WR_CONFIG, hello_fpga::HE_WR_NUM_LINES, hello_fpga_data_intg_check(), hello_fpga::HELLO_FPGA_NUMCACHE_LINES, hello_fpga::he_cmd::host_exe_, hello_fpga::he_cmd::host_exerciser_errors(), hello_fpga::he_cmd::numa_node_, opae::afu_test::afu::read64(), hello_fpga::he_info::value, hello_fpga::he_wr_config::value, hello_fpga::he_wr_addr_table_ctrl::value, hello_fpga::WR_LINE_M, hello_fpga::he_cmd::wr_table_ctl_, and opae::afu_test::afu::write64().
Referenced by run().
virtual int hello_fpga::he_cache_cmd::run (test_afu * afu, CLI::App * app) [inline], [virtual]
Implements opae::afu_test::command.
Definition at line 238 of file cxl_hello_fpga_cmd.h.
References app, hello_fpga::HE_CTL, hello_fpga::he_cmd::he_ctl_, hello_fpga::HE_HELLO_FPGA, he_run_hello_fpga_test(), he_test_, hello_fpga::he_cmd::host_exe_, hello_fpga::he_cmd::numa_node_, hello_fpga::he_cmd::print_csr(), hello_fpga::he_ctl::value, hello_fpga::he_cmd::verify_numa_node(), and opae::afu_test::afu::write64().
Field Documentation
uint32_t hello_fpga::he_cache_cmd::he_test_ [protected]
Definition at line 268 of file cxl_hello_fpga_cmd.h.
Referenced by run().
Author
Generated automatically by Doxygen for OPAE C API from the source code.