host_exerciser::he_cache_cmd
NAME
host_exerciser::he_cache_cmd
SYNOPSIS
#include </root/samples/cxl_host_exerciser/cxl_he_cache_cmd.h>
Inherits host_exerciser::he_cmd.
Public Member Functions
he_cache_cmd ()
virtual ~he_cache_cmd ()
virtual const char * name () const override
virtual const char * description () const override
virtual const char * afu_id () const override
virtual uint64_t featureid () const override
virtual uint64_t guidl () const override
virtual uint64_t guidh () const override
virtual void add_options (CLI::App *app) override
int he_run_fpga_rd_cache_hit_test ()
int he_run_fpga_wr_cache_hit_test ()
int he_run_fpga_rd_cache_miss_test ()
int he_run_fpga_wr_cache_miss_test ()
int he_run_host_rd_cache_hit_test ()
int he_run_host_wr_cache_hit_test ()
void he_forcetestcmpl ()
int he_run_running_pointer_test ()
int he_run_ping_pong_test ()
bool he_continuousmode ()
bool verify_input_options ()
virtual int run (test_afu *afu, CLI::App *app)
Protected Attributes
bool he_continuousmode_
uint32_t he_contmodetime_
uint32_t he_linerep_count_
uint32_t he_stride_
uint32_t he_test_
bool he_test_all_
uint32_t he_dev_instance_
bool he_stride_cmd_
uint32_t he_cls_count_
uint64_t he_latency_iterations_
uint32_t he_loop_count_
Additional Inherited Members
Detailed Description
Definition at line 50 of file cxl_he_cache_cmd.h.
Constructor & Destructor Documentation
host_exerciser::he_cache_cmd::he_cache_cmd () [inline]
Definition at line 52 of file cxl_he_cache_cmd.h.
virtual host_exerciser::he_cache_cmd::~he_cache_cmd () [inline], [virtual]
Definition at line 58 of file cxl_he_cache_cmd.h.
Member Function Documentation
virtual const char* host_exerciser::he_cache_cmd::name () const [inline], [override], [virtual]
Implements opae::afu_test::command.
Definition at line 60 of file cxl_he_cache_cmd.h.
virtual const char* host_exerciser::he_cache_cmd::description () const [inline], [override], [virtual]
Implements opae::afu_test::command.
Definition at line 62 of file cxl_he_cache_cmd.h.
virtual const char* host_exerciser::he_cache_cmd::afu_id () const [inline], [override], [virtual]
Reimplemented from opae::afu_test::command.
Definition at line 66 of file cxl_he_cache_cmd.h.
References HE_CACHE_AFU_ID.
virtual uint64_t host_exerciser::he_cache_cmd::featureid () const [inline], [override], [virtual]
Implements opae::afu_test::command.
Definition at line 68 of file cxl_he_cache_cmd.h.
References MEM_TG_FEATURE_ID.
virtual uint64_t host_exerciser::he_cache_cmd::guidl () const [inline], [override], [virtual]
Implements opae::afu_test::command.
Definition at line 70 of file cxl_he_cache_cmd.h.
References MEM_TG_FEATURE_GUIDL.
virtual uint64_t host_exerciser::he_cache_cmd::guidh () const [inline], [override], [virtual]
Implements opae::afu_test::command.
Definition at line 72 of file cxl_he_cache_cmd.h.
References MEM_TG_FEATURE_GUIDH.
virtual void host_exerciser::he_cache_cmd::add_options (CLI::App * app) [inline], [override], [virtual]
Reimplemented from opae::afu_test::command.
Definition at line 74 of file cxl_he_cache_cmd.h.
References app, host_exerciser::he_bias, host_exerciser::he_cmd::he_bias_, he_cls_count_, he_continuousmode_, he_contmodetime_, host_exerciser::he_cxl_device, he_dev_instance_, he_latency_iterations_, he_linerep_count_, he_loop_count_, he_stride_, host_exerciser::he_cmd::he_target_, host_exerciser::he_targets, he_test_, and host_exerciser::he_test_modes.
int host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test () [inline]
Definition at line 138 of file cxl_he_cache_cmd.h.
References opae::afu_test::afu::allocate_cache_read(), opae::afu_test::afu::allocate_dsm(), host_exerciser::BUFFER_SIZE_2MB, opae::afu_test::afu::free_cache_read(), opae::afu_test::afu::free_dsm(), host_exerciser::he_cmd::get_penalty_start_ticks(), host_exerciser::he_cmd::get_ticks(), he_cls_count_, he_continuousmode(), he_continuousmode_, host_exerciser::HE_CXL_RD_LATENCY, host_exerciser::HE_INFO, host_exerciser::he_cmd::he_info_, he_latency_iterations_, he_linerep_count_, he_loop_count_, host_exerciser::he_cmd::he_perf_counters(), HE_PRTEST_SCENARIO, host_exerciser::HE_RD_ADDR_TABLE_CTRL, host_exerciser::he_cmd::he_rd_cfg_, host_exerciser::HE_RD_CONFIG, host_exerciser::HE_RD_NUM_LINES, host_exerciser::he_cmd::he_start_test(), he_stride_, he_stride_cmd_, host_exerciser::he_cmd::he_target_, host_exerciser::HE_TARGET_FPGA, host_exerciser::he_cmd::he_wait_test_completion(), host_exerciser::he_cmd::host_exe_, host_exerciser::he_cmd::host_exerciser_errors(), host_exerciser::LATENCY_FACTOR, opae::afu_test::afu::logger_, host_exerciser::he_cmd::numa_node_, host_exerciser::RD_LINE_S, host_exerciser::he_cmd::rd_table_ctl_, opae::afu_test::afu::read64(), opae::afu_test::afu::reset_dsm(), host_exerciser::he_info::value, host_exerciser::he_rd_config::value, host_exerciser::he_rd_addr_table_ctrl::value, and opae::afu_test::afu::write64().
Referenced by run().
int host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test () [inline]
Definition at line 312 of file cxl_he_cache_cmd.h.
References opae::afu_test::afu::allocate_cache_read_write(), opae::afu_test::afu::allocate_dsm(), host_exerciser::BUFFER_SIZE_2MB, opae::afu_test::afu::free_cache_read_write(), opae::afu_test::afu::free_dsm(), he_cls_count_, he_continuousmode(), he_continuousmode_, host_exerciser::HE_INFO, host_exerciser::he_cmd::he_info_, he_linerep_count_, he_loop_count_, host_exerciser::he_cmd::he_perf_counters(), HE_PRTEST_SCENARIO, host_exerciser::HE_RD_ADDR_TABLE_CTRL, host_exerciser::he_cmd::he_rd_cfg_, host_exerciser::HE_RD_CONFIG, host_exerciser::HE_RD_NUM_LINES, host_exerciser::he_cmd::he_start_test(), he_stride_, he_stride_cmd_, host_exerciser::he_cmd::he_target_, host_exerciser::HE_TARGET_FPGA, host_exerciser::he_cmd::he_wait_test_completion(), host_exerciser::HE_WR_ADDR_TABLE_CTRL, host_exerciser::he_cmd::he_wr_cfg_, host_exerciser::HE_WR_CONFIG, host_exerciser::HE_WR_NUM_LINES, host_exerciser::he_cmd::host_exe_, host_exerciser::he_cmd::host_exerciser_errors(), host_exerciser::he_cmd::numa_node_, host_exerciser::RD_LINE_S, host_exerciser::he_cmd::rd_table_ctl_, opae::afu_test::afu::read64(), opae::afu_test::afu::reset_dsm(), host_exerciser::he_info::value, host_exerciser::he_wr_config::value, host_exerciser::he_wr_addr_table_ctrl::value, host_exerciser::he_rd_config::value, host_exerciser::he_rd_addr_table_ctrl::value, host_exerciser::WR_LINE_M, host_exerciser::he_cmd::wr_table_ctl_, and opae::afu_test::afu::write64().
Referenced by run().
int host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test () [inline]
Definition at line 466 of file cxl_he_cache_cmd.h.
References opae::afu_test::afu::allocate_cache_read(), opae::afu_test::afu::allocate_dsm(), host_exerciser::BUFFER_SIZE_2MB, opae::afu_test::afu::free_cache_read(), opae::afu_test::afu::free_dsm(), host_exerciser::he_cmd::get_penalty_start_ticks(), host_exerciser::he_cmd::get_ticks(), he_cls_count_, he_continuousmode(), he_continuousmode_, host_exerciser::HE_CXL_RD_LATENCY, host_exerciser::HE_INFO, host_exerciser::he_cmd::he_info_, he_latency_iterations_, he_linerep_count_, he_loop_count_, host_exerciser::he_cmd::he_perf_counters(), host_exerciser::HE_RD_ADDR_TABLE_CTRL, host_exerciser::he_cmd::he_rd_cfg_, host_exerciser::HE_RD_CONFIG, host_exerciser::HE_RD_NUM_LINES, host_exerciser::he_cmd::he_start_test(), he_stride_, he_stride_cmd_, host_exerciser::he_cmd::he_target_, host_exerciser::HE_TARGET_FPGA, host_exerciser::he_cmd::he_wait_test_completion(), host_exerciser::he_cmd::host_exe_, host_exerciser::he_cmd::host_exerciser_errors(), host_exerciser::LATENCY_FACTOR, opae::afu_test::afu::logger_, host_exerciser::he_cmd::numa_node_, host_exerciser::RD_LINE_I, host_exerciser::he_cmd::rd_table_ctl_, opae::afu_test::afu::read64(), host_exerciser::he_info::value, host_exerciser::he_rd_config::value, host_exerciser::he_rd_addr_table_ctrl::value, and opae::afu_test::afu::write64().
Referenced by run().
int host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test () [inline]
Definition at line 597 of file cxl_he_cache_cmd.h.
References opae::afu_test::afu::allocate_cache_write(), opae::afu_test::afu::allocate_dsm(), host_exerciser::BUFFER_SIZE_2MB, opae::afu_test::afu::free_cache_write(), opae::afu_test::afu::free_dsm(), he_cls_count_, he_continuousmode(), he_continuousmode_, host_exerciser::HE_INFO, host_exerciser::he_cmd::he_info_, he_linerep_count_, he_loop_count_, host_exerciser::he_cmd::he_perf_counters(), host_exerciser::he_cmd::he_start_test(), he_stride_, he_stride_cmd_, host_exerciser::he_cmd::he_target_, host_exerciser::HE_TARGET_FPGA, host_exerciser::he_cmd::he_wait_test_completion(), host_exerciser::HE_WR_ADDR_TABLE_CTRL, host_exerciser::he_cmd::he_wr_cfg_, host_exerciser::HE_WR_CONFIG, host_exerciser::HE_WR_NUM_LINES, host_exerciser::he_cmd::host_exe_, host_exerciser::he_cmd::host_exerciser_errors(), host_exerciser::he_cmd::numa_node_, opae::afu_test::afu::read64(), host_exerciser::he_info::value, host_exerciser::he_wr_config::value, host_exerciser::he_wr_addr_table_ctrl::value, host_exerciser::WR_LINE_I, host_exerciser::he_cmd::wr_table_ctl_, and opae::afu_test::afu::write64().
Referenced by run().
int host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test () [inline]
Definition at line 699 of file cxl_he_cache_cmd.h.
References opae::afu_test::afu::allocate_cache_read(), opae::afu_test::afu::allocate_dsm(), host_exerciser::BUFFER_SIZE_2MB, host_exerciser::BUFFER_SIZE_32KB, opae::afu_test::afu::free_cache_read(), opae::afu_test::afu::free_dsm(), g_stop_thread, host_exerciser::he_cmd::get_penalty_start_ticks(), opae::afu_test::afu::get_read(), host_exerciser::he_cmd::get_ticks(), host_exerciser::he_cache_thread(), he_cls_count_, he_continuousmode(), he_continuousmode_, host_exerciser::HE_CXL_RD_LATENCY, host_exerciser::HE_INFO, host_exerciser::he_cmd::he_info_, he_latency_iterations_, he_linerep_count_, he_loop_count_, host_exerciser::he_cmd::he_perf_counters(), host_exerciser::HE_RD_ADDR_TABLE_CTRL, host_exerciser::he_cmd::he_rd_cfg_, host_exerciser::HE_RD_CONFIG, host_exerciser::HE_RD_NUM_LINES, host_exerciser::he_cmd::he_start_test(), he_stride_, host_exerciser::he_cmd::he_wait_test_completion(), host_exerciser::he_cmd::host_exe_, host_exerciser::he_cmd::host_exerciser_errors(), host_exerciser::LATENCY_FACTOR, opae::afu_test::afu::logger_, host_exerciser::he_cmd::numa_node_, host_exerciser::RD_LINE_I, host_exerciser::he_cmd::rd_table_ctl_, opae::afu_test::afu::read64(), host_exerciser::he_info::value, host_exerciser::he_rd_config::value, host_exerciser::he_rd_addr_table_ctrl::value, and opae::afu_test::afu::write64().
Referenced by run().
int host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test () [inline]
Definition at line 841 of file cxl_he_cache_cmd.h.
References opae::afu_test::afu::allocate_cache_write(), opae::afu_test::afu::allocate_dsm(), host_exerciser::BUFFER_SIZE_2MB, host_exerciser::BUFFER_SIZE_32KB, opae::afu_test::afu::free_cache_write(), opae::afu_test::afu::free_dsm(), g_stop_thread, opae::afu_test::afu::get_write(), host_exerciser::he_cache_thread(), he_cls_count_, he_continuousmode(), he_continuousmode_, host_exerciser::HE_INFO, host_exerciser::he_cmd::he_info_, he_linerep_count_, he_loop_count_, host_exerciser::he_cmd::he_perf_counters(), host_exerciser::he_cmd::he_start_test(), he_stride_, host_exerciser::he_cmd::he_wait_test_completion(), host_exerciser::HE_WR_ADDR_TABLE_CTRL, host_exerciser::he_cmd::he_wr_cfg_, host_exerciser::HE_WR_CONFIG, host_exerciser::HE_WR_NUM_LINES, host_exerciser::he_cmd::host_exe_, host_exerciser::he_cmd::host_exerciser_errors(), host_exerciser::he_cmd::numa_node_, opae::afu_test::afu::read64(), host_exerciser::he_info::value, host_exerciser::he_wr_config::value, host_exerciser::he_wr_addr_table_ctrl::value, host_exerciser::WR_PUSH_I, host_exerciser::he_cmd::wr_table_ctl_, and opae::afu_test::afu::write64().
Referenced by run().
void host_exerciser::he_cache_cmd::he_forcetestcmpl () [inline]
Definition at line 946 of file cxl_he_cache_cmd.h.
References host_exerciser::HE_CTL, host_exerciser::he_cmd::he_ctl_, host_exerciser::he_cmd::he_wait_test_completion(), host_exerciser::he_cmd::host_exe_, usleep(), host_exerciser::he_ctl::value, and opae::afu_test::afu::write64().
Referenced by he_continuousmode(), and he_run_ping_pong_test().
int host_exerciser::he_cache_cmd::he_run_running_pointer_test () [inline]
Definition at line 962 of file cxl_he_cache_cmd.h.
References host_exerciser::he_cmd::__mem_virt2phys(), opae::afu_test::afu::allocate_dsm(), opae::afu_test::afu::allocate_pinned_buffer(), host_exerciser::BUFFER_SIZE_2MB, host_exerciser::he_cmd::create_linked_list(), host_exerciser::FPGA_2MB_CACHE_LINES, host_exerciser::FPGAMEM_HOST_BIAS, opae::afu_test::afu::free_dsm(), opae::afu_test::afu::free_pinned_buffer(), host_exerciser::he_cmd::he_ctl_, host_exerciser::he_cmd::he_perf_counters(), host_exerciser::HE_RD_ADDR_TABLE_DATA, host_exerciser::HE_RD_NUM_LINES, host_exerciser::he_cmd::he_rd_num_lines_, HE_RUNNING_POINTER, host_exerciser::he_cmd::he_start_test(), host_exerciser::he_cmd::he_target_, host_exerciser::HE_TARGET_FPGA, host_exerciser::HE_TARGET_HOST, host_exerciser::he_cmd::he_wait_test_completion(), host_exerciser::he_cmd::host_exe_, host_exerciser::he_cmd::host_exerciser_errors(), host_exerciser::HOSTMEM_BIAS, opae::afu_test::afu::logger_, host_exerciser::he_cmd::numa_node_, opae::afu_test::afu::read64(), RUNNIG_PTR_DATA_PATTERN, host_exerciser::RUNNING_POINTER, host_exerciser::he_rd_num_lines::value, host_exerciser::he_cmd::verify_linked_list(), and opae::afu_test::afu::write64().
Referenced by run().
int host_exerciser::he_cache_cmd::he_run_ping_pong_test () [inline]
Definition at line 1146 of file cxl_he_cache_cmd.h.
References opae::afu_test::afu::allocate_cache_read(), opae::afu_test::afu::allocate_dsm(), host_exerciser::BUFFER_SIZE_2MB, opae::afu_test::afu::free_cache_read(), opae::afu_test::afu::free_dsm(), opae::afu_test::afu::get_read(), host_exerciser::HE_CACHE_TEST_SLEEP_INVL, host_exerciser::HE_CACHE_TEST_TIMEOUT, he_forcetestcmpl(), host_exerciser::he_cmd::he_perf_counters(), HE_PING_PONG, host_exerciser::HE_RD_NUM_LINES, host_exerciser::he_cmd::he_rd_num_lines_, host_exerciser::he_cmd::he_start_test(), host_exerciser::he_cmd::he_wait_test_completion(), host_exerciser::he_cmd::host_exe_, host_exerciser::he_cmd::host_exerciser_errors(), opae::afu_test::afu::logger_, host_exerciser::he_cmd::numa_node_, host_exerciser::PING_PONG, opae::afu_test::afu::read64(), usleep(), host_exerciser::he_rd_num_lines::value, and opae::afu_test::afu::write64().
Referenced by run().
bool host_exerciser::he_cache_cmd::he_continuousmode () [inline]
Definition at line 1228 of file cxl_he_cache_cmd.h.
References g_he_exit, he_continuousmode_, he_contmodetime_, he_forcetestcmpl(), host_exerciser::he_cmd::host_exe_, and opae::afu_test::afu::logger_.
Referenced by he_run_fpga_rd_cache_hit_test(), he_run_fpga_rd_cache_miss_test(), he_run_fpga_wr_cache_hit_test(), he_run_fpga_wr_cache_miss_test(), he_run_host_rd_cache_hit_test(), and he_run_host_wr_cache_hit_test().
bool host_exerciser::he_cache_cmd::verify_input_options () [inline]
Definition at line 1248 of file cxl_he_cache_cmd.h.
References host_exerciser::HE_CACHE_PING_PONG, host_exerciser::HE_FPGA_RD_CACHE_HIT, host_exerciser::HE_FPGA_RD_CACHE_MISS, host_exerciser::HE_FPGA_WR_CACHE_HIT, host_exerciser::HE_FPGA_WR_CACHE_MISS, host_exerciser::HE_HOST_RD_CACHE_HIT, host_exerciser::HE_HOST_WR_CACHE_HIT, host_exerciser::he_cmd::he_target_, host_exerciser::HE_TARGET_BOTH, and he_test_.
Referenced by run().
virtual int host_exerciser::he_cache_cmd::run (test_afu * afu, CLI::App * app) [inline], [virtual]
Implements opae::afu_test::command.
Definition at line 1267 of file cxl_he_cache_cmd.h.
References app, host_exerciser::HE_CACHE_PING_PONG, host_exerciser::HE_CACHE_RUNNING_POINTER, host_exerciser::HE_CTL, host_exerciser::he_cmd::he_ctl_, host_exerciser::HE_FPGA_RD_CACHE_HIT, host_exerciser::HE_FPGA_RD_CACHE_MISS, host_exerciser::HE_FPGA_WR_CACHE_HIT, host_exerciser::HE_FPGA_WR_CACHE_MISS, host_exerciser::HE_HOST_RD_CACHE_HIT, host_exerciser::HE_HOST_WR_CACHE_HIT, he_run_fpga_rd_cache_hit_test(), he_run_fpga_rd_cache_miss_test(), he_run_fpga_wr_cache_hit_test(), he_run_fpga_wr_cache_miss_test(), he_run_host_rd_cache_hit_test(), he_run_host_wr_cache_hit_test(), he_run_ping_pong_test(), he_run_running_pointer_test(), host_exerciser::he_cmd::he_set_bias_mode(), he_stride_cmd_, he_test_, host_exerciser::he_cmd::host_exe_, host_exerciser::he_cmd::numa_node_, host_exerciser::he_cmd::print_csr(), host_exerciser::he_ctl::value, verify_input_options(), host_exerciser::he_cmd::verify_numa_node(), and opae::afu_test::afu::write64().
Field Documentation
bool host_exerciser::he_cache_cmd::he_continuousmode_ [protected]
Definition at line 1346 of file cxl_he_cache_cmd.h.
Referenced by add_options(), he_continuousmode(), he_run_fpga_rd_cache_hit_test(), he_run_fpga_rd_cache_miss_test(), he_run_fpga_wr_cache_hit_test(), he_run_fpga_wr_cache_miss_test(), he_run_host_rd_cache_hit_test(), and he_run_host_wr_cache_hit_test().
uint32_t host_exerciser::he_cache_cmd::he_contmodetime_ [protected]
Definition at line 1347 of file cxl_he_cache_cmd.h.
Referenced by add_options(), and he_continuousmode().
uint32_t host_exerciser::he_cache_cmd::he_linerep_count_ [protected]
Definition at line 1348 of file cxl_he_cache_cmd.h.
Referenced by add_options(), he_run_fpga_rd_cache_hit_test(), he_run_fpga_rd_cache_miss_test(), he_run_fpga_wr_cache_hit_test(), he_run_fpga_wr_cache_miss_test(), he_run_host_rd_cache_hit_test(), and he_run_host_wr_cache_hit_test().
uint32_t host_exerciser::he_cache_cmd::he_stride_ [protected]
Definition at line 1349 of file cxl_he_cache_cmd.h.
Referenced by add_options(), he_run_fpga_rd_cache_hit_test(), he_run_fpga_rd_cache_miss_test(), he_run_fpga_wr_cache_hit_test(), he_run_fpga_wr_cache_miss_test(), he_run_host_rd_cache_hit_test(), and he_run_host_wr_cache_hit_test().
uint32_t host_exerciser::he_cache_cmd::he_test_ [protected]
Definition at line 1350 of file cxl_he_cache_cmd.h.
Referenced by add_options(), run(), and verify_input_options().
bool host_exerciser::he_cache_cmd::he_test_all_ [protected]
Definition at line 1351 of file cxl_he_cache_cmd.h.
uint32_t host_exerciser::he_cache_cmd::he_dev_instance_ [protected]
Definition at line 1352 of file cxl_he_cache_cmd.h.
Referenced by add_options().
bool host_exerciser::he_cache_cmd::he_stride_cmd_ [protected]
Definition at line 1353 of file cxl_he_cache_cmd.h.
Referenced by he_run_fpga_rd_cache_hit_test(), he_run_fpga_rd_cache_miss_test(), he_run_fpga_wr_cache_hit_test(), he_run_fpga_wr_cache_miss_test(), and run().
uint32_t host_exerciser::he_cache_cmd::he_cls_count_ [protected]
Definition at line 1354 of file cxl_he_cache_cmd.h.
Referenced by add_options(), he_run_fpga_rd_cache_hit_test(), he_run_fpga_rd_cache_miss_test(), he_run_fpga_wr_cache_hit_test(), he_run_fpga_wr_cache_miss_test(), he_run_host_rd_cache_hit_test(), and he_run_host_wr_cache_hit_test().
uint64_t host_exerciser::he_cache_cmd::he_latency_iterations_ [protected]
Definition at line 1355 of file cxl_he_cache_cmd.h.
Referenced by add_options(), he_run_fpga_rd_cache_hit_test(), he_run_fpga_rd_cache_miss_test(), and he_run_host_rd_cache_hit_test().
uint32_t host_exerciser::he_cache_cmd::he_loop_count_ [protected]
Definition at line 1356 of file cxl_he_cache_cmd.h.
Referenced by add_options(), he_run_fpga_rd_cache_hit_test(), he_run_fpga_rd_cache_miss_test(), he_run_fpga_wr_cache_hit_test(), he_run_fpga_wr_cache_miss_test(), he_run_host_rd_cache_hit_test(), and he_run_host_wr_cache_hit_test().
Author
Generated automatically by Doxygen for OPAE C API from the source code.