host_exerciser::he_cmd
NAME
host_exerciser::he_cmd
SYNOPSIS
#include </root/samples/cxl_host_exerciser/cxl_he_cmd.h>
Inherits opae::afu_test::command.
Inherited by host_exerciser::he_cache_cmd.
Public Member Functions
he_cmd ()
virtual ~he_cmd ()
double he_num_xfers_to_bw (uint64_t num_lines, uint64_t num_ticks)
void he_perf_counters (he_cxl_latency cxl_latency=HE_CXL_LATENCY_NONE)
void print_csr ()
void host_exerciser_errors ()
int parse_input_options ()
bool he_wait_test_completion ()
bool he_set_bias_mode ()
void he_start_test (const char *str='Test started ......', uint8_t test_type=RD_WR_TEST)
bool verify_numa_node ()
bool he_get_perf (double *perf_data, double *latency, he_cxl_latency cxl_latency=HE_CXL_LATENCY_NONE)
uint64_t get_ticks ()
uint64_t get_penalty_start_ticks ()
int get_mtime (const char *file_name, struct timespec *mtime)
int file_open (const char *file_name, int mode)
uint64_t __mem_virt2phys (const void *virtaddr)
bool create_linked_list (uint64_t *virt_ptr_a, uint64_t phy_ptr_a, uint64_t data, uint64_t max_size, he_bias_support bias_a=HOSTMEM_BIAS, uint64_t *virt_ptr_b=NULL, uint64_t phy_ptr_b=0, he_bias_support bias_b=FPGAMEM_HOST_BIAS)
bool verify_linked_list (uint64_t *virt_ptr, uint64_t phy_ptr, uint64_t data, uint64_t max_size)
bool print_linked_list (uint64_t *virt_ptr, uint64_t phy_ptr, uint64_t data, uint64_t max_size)
Protected Attributes
host_exerciser * host_exe_
uint32_t he_clock_mhz_
uint32_t numa_node_
uint32_t he_target_
uint32_t he_bias_
he_ctl he_ctl_
he_info he_info_
he_rd_config he_rd_cfg_
he_wr_config he_wr_cfg_
he_rd_addr_table_ctrl rd_table_ctl_
he_wr_addr_table_ctrl wr_table_ctl_
he_rd_num_lines he_rd_num_lines_
Additional Inherited Members
Detailed Description
Definition at line 44 of file cxl_he_cmd.h.
Constructor & Destructor Documentation
host_exerciser::he_cmd::he_cmd () [inline]
Definition at line 46 of file cxl_he_cmd.h.
References he_ctl_, he_info_, he_rd_cfg_, he_rd_num_lines_, he_wr_cfg_, rd_table_ctl_, host_exerciser::he_ctl::value, host_exerciser::he_info::value, host_exerciser::he_wr_config::value, host_exerciser::he_wr_addr_table_ctrl::value, host_exerciser::he_rd_num_lines::value, host_exerciser::he_rd_config::value, host_exerciser::he_rd_addr_table_ctrl::value, and wr_table_ctl_.
virtual host_exerciser::he_cmd::~he_cmd () [inline], [virtual]
Definition at line 58 of file cxl_he_cmd.h.
Member Function Documentation
double host_exerciser::he_cmd::he_num_xfers_to_bw (uint64_t num_lines, uint64_t num_ticks) [inline]
Definition at line 61 of file cxl_he_cmd.h.
References he_clock_mhz_.
Referenced by he_get_perf(), and he_perf_counters().
void host_exerciser::he_cmd::he_perf_counters (he_cxl_latency cxl_latency = HE_CXL_LATENCY_NONE) [inline]
Definition at line 65 of file cxl_he_cmd.h.
References host_exerciser::he_cache_dsm_status::actual_data, host_exerciser::he_cache_dsm_status::dsm_number, host_exerciser::he_cache_dsm_status::err_vector, host_exerciser::he_cache_dsm_status::expected_data, opae::afu_test::afu::get_dsm(), host_exerciser::HE_CXL_RD_LATENCY, he_num_xfers_to_bw(), host_exe_, opae::afu_test::afu::logger_, host_exerciser::he_cache_dsm_status::num_reads, host_exerciser::he_cache_dsm_status::num_ticks, host_exerciser::he_cache_dsm_status::num_writes, host_exerciser::he_cache_dsm_status::penalty_end, host_exerciser::he_cache_dsm_status::penalty_start, and host_exerciser::he_cache_dsm_status::test_completed.
Referenced by host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_ping_pong_test(), and host_exerciser::he_cache_cmd::he_run_running_pointer_test().
void host_exerciser::he_cmd::print_csr () [inline]
Definition at line 107 of file cxl_he_cmd.h.
References host_exerciser::HE_CTL, host_exerciser::HE_DFH, host_exerciser::HE_DSM_BASE, host_exerciser::HE_ERROR_ACT_DATA0, host_exerciser::HE_ERROR_ACT_DATA1, host_exerciser::HE_ERROR_ACT_DATA2, host_exerciser::HE_ERROR_ACT_DATA3, host_exerciser::HE_ERROR_ACT_DATA4, host_exerciser::HE_ERROR_ACT_DATA5, host_exerciser::HE_ERROR_ACT_DATA6, host_exerciser::HE_ERROR_ACT_DATA7, host_exerciser::HE_ERROR_EXP_DATA, host_exerciser::HE_ERROR_STATUS, host_exerciser::HE_ID_H, host_exerciser::HE_ID_L, host_exerciser::HE_INFO, host_exerciser::HE_RD_ADDR_TABLE_CTRL, host_exerciser::HE_RD_ADDR_TABLE_DATA, host_exerciser::HE_RD_CONFIG, host_exerciser::HE_RD_NUM_LINES, host_exerciser::HE_SCRATCHPAD0, host_exerciser::HE_WR_ADDR_TABLE_CTRL, host_exerciser::HE_WR_ADDR_TABLE_DATA, host_exerciser::HE_WR_BYTE_ENABLE, host_exerciser::HE_WR_CONFIG, host_exerciser::HE_WR_NUM_LINES, host_exe_, opae::afu_test::afu::logger_, and opae::afu_test::afu::read64().
Referenced by host_exerciser::he_cache_cmd::run().
void host_exerciser::he_cmd::host_exerciser_errors () [inline]
Definition at line 181 of file cxl_he_cmd.h.
References host_exerciser::HE_ERROR_ACT_DATA0, host_exerciser::HE_ERROR_ACT_DATA1, host_exerciser::HE_ERROR_ACT_DATA2, host_exerciser::HE_ERROR_ACT_DATA3, host_exerciser::HE_ERROR_ACT_DATA4, host_exerciser::HE_ERROR_ACT_DATA5, host_exerciser::HE_ERROR_ACT_DATA6, host_exerciser::HE_ERROR_ACT_DATA7, host_exerciser::HE_ERROR_EXP_DATA, host_exerciser::HE_ERROR_STATUS, host_exe_, opae::afu_test::afu::read64(), and host_exerciser::he_err_status::value.
Referenced by host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_ping_pong_test(), and host_exerciser::he_cache_cmd::he_run_running_pointer_test().
int host_exerciser::he_cmd::parse_input_options () [inline]
Definition at line 225 of file cxl_he_cmd.h.
References host_exe_.
bool host_exerciser::he_cmd::he_wait_test_completion () [inline]
Definition at line 233 of file cxl_he_cmd.h.
References opae::afu_test::afu::get_dsm(), host_exerciser::HE_CACHE_TEST_SLEEP_INVL, host_exerciser::HE_CACHE_TEST_TIMEOUT, host_exe_, and usleep().
Referenced by host_exerciser::he_cache_cmd::he_forcetestcmpl(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_ping_pong_test(), and host_exerciser::he_cache_cmd::he_run_running_pointer_test().
bool host_exerciser::he_cmd::he_set_bias_mode () [inline]
Definition at line 248 of file cxl_he_cmd.h.
References host_exerciser::FPGAMEM_DEVICE_BIAS, host_exerciser::FPGAMEM_HOST_BIAS, he_bias_, HE_CACHE_DMA_MMAP_R, he_ctl_, he_target_, host_exerciser::HE_TARGET_HOST, host_exe_, host_exerciser::HOSTMEM_BIAS, and opae::afu_test::afu::set_mmap_access().
Referenced by host_exerciser::he_cache_cmd::run().
void host_exerciser::he_cmd::he_start_test (const char * str = 'Test started ......', uint8_t test_type = RD_WR_TEST) [inline]
Definition at line 274 of file cxl_he_cmd.h.
References host_exerciser::HE_CTL, he_ctl_, host_exe_, opae::afu_test::afu::logger_, opae::afu_test::afu::read64(), host_exerciser::he_ctl::value, and opae::afu_test::afu::write64().
Referenced by host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_ping_pong_test(), and host_exerciser::he_cache_cmd::he_run_running_pointer_test().
bool host_exerciser::he_cmd::verify_numa_node () [inline]
Definition at line 291 of file cxl_he_cmd.h.
References he_target_, host_exerciser::HE_TARGET_HOST, and numa_node_.
Referenced by host_exerciser::he_cache_cmd::run().
bool host_exerciser::he_cmd::he_get_perf (double * perf_data, double * latency, he_cxl_latency cxl_latency = HE_CXL_LATENCY_NONE) [inline]
Definition at line 317 of file cxl_he_cmd.h.
References opae::afu_test::afu::get_dsm(), host_exerciser::HE_CXL_RD_LATENCY, he_num_xfers_to_bw(), host_exe_, host_exerciser::he_cache_dsm_status::num_reads, host_exerciser::he_cache_dsm_status::num_ticks, and host_exerciser::he_cache_dsm_status::num_writes.
uint64_t host_exerciser::he_cmd::get_ticks () [inline]
Definition at line 342 of file cxl_he_cmd.h.
References opae::afu_test::afu::get_dsm(), host_exe_, and host_exerciser::he_cache_dsm_status::num_ticks.
Referenced by host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), and host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test().
uint64_t host_exerciser::he_cmd::get_penalty_start_ticks () [inline]
Definition at line 355 of file cxl_he_cmd.h.
References opae::afu_test::afu::get_dsm(), host_exe_, and host_exerciser::he_cache_dsm_status::penalty_start.
Referenced by host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), and host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test().
int host_exerciser::he_cmd::get_mtime (const char * file_name, struct timespec * mtime) [inline]
Definition at line 368 of file cxl_he_cmd.h.
Referenced by __mem_virt2phys().
int host_exerciser::he_cmd::file_open (const char * file_name, int mode) [inline]
Definition at line 387 of file cxl_he_cmd.h.
Referenced by __mem_virt2phys().
uint64_t host_exerciser::he_cmd::__mem_virt2phys (const void * virtaddr) [inline]
Definition at line 418 of file cxl_he_cmd.h.
References file_open(), get_mtime(), and PFN_MASK_SIZE.
Referenced by host_exerciser::he_cache_cmd::he_run_running_pointer_test().
bool host_exerciser::he_cmd::create_linked_list (uint64_t * virt_ptr_a, uint64_t phy_ptr_a, uint64_t data, uint64_t max_size, he_bias_support bias_a = HOSTMEM_BIAS, uint64_t * virt_ptr_b = NULL, uint64_t phy_ptr_b = 0, he_bias_support bias_b = FPGAMEM_HOST_BIAS) [inline]
Definition at line 471 of file cxl_he_cmd.h.
References host_exerciser::he_cache_running_ptr::data, host_exe_, opae::afu_test::afu::logger_, host_exerciser::he_cache_running_ptr::phy_next_ptr, and host_exerciser::he_cache_running_ptr::virt_next_ptr.
Referenced by host_exerciser::he_cache_cmd::he_run_running_pointer_test().
bool host_exerciser::he_cmd::verify_linked_list (uint64_t * virt_ptr, uint64_t phy_ptr, uint64_t data, uint64_t max_size) [inline]
Definition at line 560 of file cxl_he_cmd.h.
References host_exerciser::he_cache_running_ptr::data, host_exe_, opae::afu_test::afu::logger_, and host_exerciser::he_cache_running_ptr::virt_next_ptr.
Referenced by host_exerciser::he_cache_cmd::he_run_running_pointer_test().
bool host_exerciser::he_cmd::print_linked_list (uint64_t * virt_ptr, uint64_t phy_ptr, uint64_t data, uint64_t max_size) [inline]
Definition at line 591 of file cxl_he_cmd.h.
References host_exerciser::he_cache_running_ptr::data, host_exe_, opae::afu_test::afu::logger_, and host_exerciser::he_cache_running_ptr::virt_next_ptr.
Field Documentation
host_exerciser* host_exerciser::he_cmd::host_exe_ [protected]
Definition at line 618 of file cxl_he_cmd.h.
Referenced by create_linked_list(), get_penalty_start_ticks(), get_ticks(), host_exerciser::he_cache_cmd::he_continuousmode(), host_exerciser::he_cache_cmd::he_forcetestcmpl(), he_get_perf(), he_perf_counters(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_ping_pong_test(), host_exerciser::he_cache_cmd::he_run_running_pointer_test(), he_set_bias_mode(), he_start_test(), he_wait_test_completion(), host_exerciser_errors(), parse_input_options(), print_csr(), print_linked_list(), host_exerciser::he_cache_cmd::run(), and verify_linked_list().
uint32_t host_exerciser::he_cmd::he_clock_mhz_ [protected]
Definition at line 619 of file cxl_he_cmd.h.
Referenced by he_num_xfers_to_bw().
uint32_t host_exerciser::he_cmd::numa_node_ [protected]
Definition at line 620 of file cxl_he_cmd.h.
Referenced by host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_ping_pong_test(), host_exerciser::he_cache_cmd::he_run_running_pointer_test(), host_exerciser::he_cache_cmd::run(), and verify_numa_node().
uint32_t host_exerciser::he_cmd::he_target_ [protected]
Definition at line 621 of file cxl_he_cmd.h.
Referenced by host_exerciser::he_cache_cmd::add_options(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_running_pointer_test(), he_set_bias_mode(), host_exerciser::he_cache_cmd::verify_input_options(), and verify_numa_node().
uint32_t host_exerciser::he_cmd::he_bias_ [protected]
Definition at line 622 of file cxl_he_cmd.h.
Referenced by host_exerciser::he_cache_cmd::add_options(), and he_set_bias_mode().
he_ctl host_exerciser::he_cmd::he_ctl_ [protected]
Definition at line 624 of file cxl_he_cmd.h.
Referenced by he_cmd(), host_exerciser::he_cache_cmd::he_forcetestcmpl(), host_exerciser::he_cache_cmd::he_run_running_pointer_test(), he_set_bias_mode(), he_start_test(), and host_exerciser::he_cache_cmd::run().
he_info host_exerciser::he_cmd::he_info_ [protected]
Definition at line 625 of file cxl_he_cmd.h.
Referenced by he_cmd(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), and host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test().
he_rd_config host_exerciser::he_cmd::he_rd_cfg_ [protected]
Definition at line 626 of file cxl_he_cmd.h.
Referenced by he_cmd(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), and host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test().
he_wr_config host_exerciser::he_cmd::he_wr_cfg_ [protected]
Definition at line 627 of file cxl_he_cmd.h.
Referenced by he_cmd(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), and host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test().
he_rd_addr_table_ctrl host_exerciser::he_cmd::rd_table_ctl_ [protected]
Definition at line 628 of file cxl_he_cmd.h.
Referenced by he_cmd(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), and host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test().
he_wr_addr_table_ctrl host_exerciser::he_cmd::wr_table_ctl_ [protected]
Definition at line 629 of file cxl_he_cmd.h.
Referenced by he_cmd(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), and host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test().
he_rd_num_lines host_exerciser::he_cmd::he_rd_num_lines_ [protected]
Definition at line 630 of file cxl_he_cmd.h.
Referenced by he_cmd(), host_exerciser::he_cache_cmd::he_run_ping_pong_test(), and host_exerciser::he_cache_cmd::he_run_running_pointer_test().
Author
Generated automatically by Doxygen for OPAE C API from the source code.