opae::afu_test::command
NAME
opae::afu_test::command
SYNOPSIS
#include </root/samples/cxl_hello_fpga/he_cache_test.h>
Inherited by cxl_mem_tg::cxl_tg_test, dummy_afu::ddr_test, dummy_afu::lpbk_test, dummy_afu::mmio_test, hello_fpga::he_cmd, host_exerciser::he_cmd, host_exerciser::host_exerciser_cmd, hssi_cmd, and mem_tg::tg_test.
Public Types
typedef std::shared_ptr< command > ptr_t
typedef std::shared_ptr< command > ptr_t
Public Member Functions
command ()
virtual ~command ()
virtual const char * name () const =0
virtual const char * description () const =0
virtual int run (afu *afu, CLI::App *app)=0
virtual void add_options (CLI::App *app)
virtual const char * afu_id () const
virtual uint64_t featureid () const =0
virtual uint64_t guidl () const =0
virtual uint64_t guidh () const =0
bool running () const
void stop ()
command ()
virtual ~command ()
virtual const char * name () const =0
virtual const char * description () const =0
virtual int run (afu *afu, CLI::App *app)=0
virtual void add_options (CLI::App *app)
virtual const char * afu_id () const
virtual uint64_t featureid () const =0
virtual uint64_t guidl () const =0
virtual uint64_t guidh () const =0
bool running () const
void stop ()
Private Attributes
std::atomic< bool > running_
Detailed Description
Definition at line 228 of file he_cache_test.h.
Member Typedef Documentation
typedef std::shared_ptr<command> opae::afu_test::command::ptr_t
Definition at line 230 of file he_cache_test.h.
typedef std::shared_ptr<command> opae::afu_test::command::ptr_t
Definition at line 240 of file he_cache_test.h.
Constructor & Destructor Documentation
opae::afu_test::command::command () [inline]
Definition at line 231 of file he_cache_test.h.
virtual opae::afu_test::command::~command () [inline], [virtual]
Definition at line 232 of file he_cache_test.h.
opae::afu_test::command::command () [inline]
Definition at line 241 of file he_cache_test.h.
virtual opae::afu_test::command::~command () [inline], [virtual]
Definition at line 242 of file he_cache_test.h.
Member Function Documentation
virtual const char* opae::afu_test::command::name () const [pure virtual]
Implemented in mem_tg::tg_test, hssi_pkt_filt_10g_cmd, hssi_pkt_filt_100g_cmd, hssi_200g_400g_cmd, hssi_10g_cmd, hssi_100g_cmd, host_exerciser::host_exerciser_mem, host_exerciser::host_exerciser_lpbk, cxl_mem_tg::cxl_tg_test, host_exerciser::he_cache_cmd, hello_fpga::he_cache_cmd, dummy_afu::mmio_test, dummy_afu::lpbk_test, and dummy_afu::ddr_test.
virtual const char* opae::afu_test::command::description () const [pure virtual]
Implemented in mem_tg::tg_test, hssi_pkt_filt_10g_cmd, hssi_pkt_filt_100g_cmd, hssi_200g_400g_cmd, hssi_10g_cmd, hssi_100g_cmd, host_exerciser::host_exerciser_mem, host_exerciser::host_exerciser_lpbk, cxl_mem_tg::cxl_tg_test, host_exerciser::he_cache_cmd, hello_fpga::he_cache_cmd, dummy_afu::mmio_test, dummy_afu::lpbk_test, and dummy_afu::ddr_test.
virtual int opae::afu_test::command::run (afu * afu, CLI::App * app) [pure virtual]
Implemented in mem_tg::tg_test, hssi_pkt_filt_10g_cmd, hssi_pkt_filt_100g_cmd, hssi_200g_400g_cmd, hssi_10g_cmd, hssi_100g_cmd, cxl_mem_tg::cxl_tg_test, host_exerciser::host_exerciser_cmd, dummy_afu::mmio_test, dummy_afu::lpbk_test, dummy_afu::ddr_test, host_exerciser::he_cache_cmd, and hello_fpga::he_cache_cmd.
virtual void opae::afu_test::command::add_options (CLI::App * app) [inline], [virtual]
Reimplemented in hssi_pkt_filt_10g_cmd, hssi_pkt_filt_100g_cmd, hssi_200g_400g_cmd, hssi_10g_cmd, hssi_100g_cmd, host_exerciser::he_cache_cmd, hello_fpga::he_cache_cmd, and dummy_afu::mmio_test.
Definition at line 236 of file he_cache_test.h.
References app.
virtual const char* opae::afu_test::command::afu_id () const [inline], [virtual]
Reimplemented in mem_tg::tg_test, hssi_200g_400g_cmd, hssi_10g_cmd, hssi_100g_cmd, host_exerciser::host_exerciser_mem, host_exerciser::host_exerciser_lpbk, cxl_mem_tg::cxl_tg_test, host_exerciser::he_cache_cmd, and hello_fpga::he_cache_cmd.
Definition at line 237 of file he_cache_test.h.
virtual uint64_t opae::afu_test::command::featureid () const [pure virtual]
Implemented in host_exerciser::he_cache_cmd, and hello_fpga::he_cache_cmd.
virtual uint64_t opae::afu_test::command::guidl () const [pure virtual]
Implemented in host_exerciser::he_cache_cmd, and hello_fpga::he_cache_cmd.
virtual uint64_t opae::afu_test::command::guidh () const [pure virtual]
Implemented in host_exerciser::he_cache_cmd, and hello_fpga::he_cache_cmd.
bool opae::afu_test::command::running () const [inline]
Definition at line 243 of file he_cache_test.h.
Referenced by hssi_100g_cmd::run(), hssi_10g_cmd::run(), and hssi_200g_400g_cmd::run().
void opae::afu_test::command::stop () [inline]
Definition at line 244 of file he_cache_test.h.
virtual const char* opae::afu_test::command::name () const [pure virtual]
Implemented in mem_tg::tg_test, hssi_pkt_filt_10g_cmd, hssi_pkt_filt_100g_cmd, hssi_200g_400g_cmd, hssi_10g_cmd, hssi_100g_cmd, host_exerciser::host_exerciser_mem, host_exerciser::host_exerciser_lpbk, cxl_mem_tg::cxl_tg_test, host_exerciser::he_cache_cmd, hello_fpga::he_cache_cmd, dummy_afu::mmio_test, dummy_afu::lpbk_test, and dummy_afu::ddr_test.
virtual const char* opae::afu_test::command::description () const [pure virtual]
Implemented in mem_tg::tg_test, hssi_pkt_filt_10g_cmd, hssi_pkt_filt_100g_cmd, hssi_200g_400g_cmd, hssi_10g_cmd, hssi_100g_cmd, host_exerciser::host_exerciser_mem, host_exerciser::host_exerciser_lpbk, cxl_mem_tg::cxl_tg_test, host_exerciser::he_cache_cmd, hello_fpga::he_cache_cmd, dummy_afu::mmio_test, dummy_afu::lpbk_test, and dummy_afu::ddr_test.
virtual int opae::afu_test::command::run (afu * afu, CLI::App * app) [pure virtual]
Implemented in mem_tg::tg_test, hssi_pkt_filt_10g_cmd, hssi_pkt_filt_100g_cmd, hssi_200g_400g_cmd, hssi_10g_cmd, hssi_100g_cmd, cxl_mem_tg::cxl_tg_test, host_exerciser::host_exerciser_cmd, dummy_afu::mmio_test, dummy_afu::lpbk_test, dummy_afu::ddr_test, host_exerciser::he_cache_cmd, and hello_fpga::he_cache_cmd.
virtual void opae::afu_test::command::add_options (CLI::App * app) [inline], [virtual]
Reimplemented in hssi_pkt_filt_10g_cmd, hssi_pkt_filt_100g_cmd, hssi_200g_400g_cmd, hssi_10g_cmd, hssi_100g_cmd, host_exerciser::he_cache_cmd, hello_fpga::he_cache_cmd, and dummy_afu::mmio_test.
Definition at line 246 of file he_cache_test.h.
References app.
virtual const char* opae::afu_test::command::afu_id () const [inline], [virtual]
Reimplemented in mem_tg::tg_test, hssi_200g_400g_cmd, hssi_10g_cmd, hssi_100g_cmd, host_exerciser::host_exerciser_mem, host_exerciser::host_exerciser_lpbk, cxl_mem_tg::cxl_tg_test, host_exerciser::he_cache_cmd, and hello_fpga::he_cache_cmd.
Definition at line 247 of file he_cache_test.h.
virtual uint64_t opae::afu_test::command::featureid () const [pure virtual]
Implemented in host_exerciser::he_cache_cmd, and hello_fpga::he_cache_cmd.
virtual uint64_t opae::afu_test::command::guidl () const [pure virtual]
Implemented in host_exerciser::he_cache_cmd, and hello_fpga::he_cache_cmd.
virtual uint64_t opae::afu_test::command::guidh () const [pure virtual]
Implemented in host_exerciser::he_cache_cmd, and hello_fpga::he_cache_cmd.
bool opae::afu_test::command::running () const [inline]
Definition at line 253 of file he_cache_test.h.
void opae::afu_test::command::stop () [inline]
Definition at line 254 of file he_cache_test.h.
Field Documentation
std::atomic< bool > opae::afu_test::command::running_ [private]
Definition at line 247 of file he_cache_test.h.
Author
Generated automatically by Doxygen for OPAE C API from the source code.