opae::afu_test::afu
NAME
opae::afu_test::afu
SYNOPSIS
#include </root/samples/cxl_hello_fpga/he_cache_test.h>
Inherited by cxl_mem_tg::cxl_mem_tg, dummy_afu::dummy_afu, hello_fpga::hello_fpga, host_exerciser::host_exerciser, host_exerciser::host_exerciser, hssi_afu, and mem_tg::mem_tg.
Public Types
enum exit_codes { success = 0, not_run, not_found, no_access, exception, error, success = 0, not_run, not_found, no_access, exception, error }
enum exit_codes { success = 0, not_run, not_found, no_access, exception, error, success = 0, not_run, not_found, no_access, exception, error }
typedef int(* command_fn) (afu *afu, CLI::App *app)
typedef int(* command_fn) (afu *afu, CLI::App *app)
Public Member Functions
afu (const char *name, const char *afu_id=nullptr, const char *log_level=nullptr)
virtual ~afu ()
CLI::App & cli ()
int find_dev_feature ()
void unmap_mmio ()
bool map_mmio ()
int open_handle (const char *dev)
int main (int argc, char *argv[])
virtual int run (CLI::App *app, command::ptr_t test)
template<class T > CLI::App * register_command ()
uint64_t read64 (uint32_t offset)
void write64 (uint32_t offset, uint64_t value)
uint32_t read32 (uint32_t offset)
void write32 (uint32_t offset, uint32_t value)
command::ptr_t current_command () const
bool allocate_dsm (size_t len=((4) *1024), uint32_t numa_node=0)
bool free_dsm ()
void reset_dsm ()
bool allocate_cache_read (size_t len=((2) *1024 *1024), uint32_t numa_node=0)
bool free_cache_read ()
bool allocate_cache_write (size_t len=((2) *1024 *1024), uint32_t numa_node=0)
bool free_cache_write ()
bool allocate_cache_read_write (size_t len=((2) *1024 *1024), uint32_t numa_node=0)
bool free_cache_read_write ()
uint8_t * get_dsm () const
uint8_t * get_read () const
uint8_t * get_write () const
uint8_t * get_read_write () const
void set_mmap_access (he_mmap_access access=HE_CACHE_DMA_MMAP_RW)
volatile uint64_t * get_write_buff_phy_addr () const
afu (const char *name, const char *afu_id=nullptr, const char *log_level=nullptr)
virtual ~afu ()
CLI::App & cli ()
int find_dev_feature ()
void unmap_mmio ()
bool map_mmio ()
int open_handle (const char *dev)
int main (int argc, char *argv[])
virtual int run (CLI::App *app, command::ptr_t test)
template<class T > CLI::App * register_command ()
uint64_t read64 (uint32_t offset)
void write64 (uint32_t offset, uint64_t value)
uint32_t read32 (uint32_t offset)
void write32 (uint32_t offset, uint32_t value)
command::ptr_t current_command () const
bool allocate_dsm (size_t len=((4) *1024), uint32_t numa_node=0)
bool free_dsm ()
void reset_dsm ()
bool allocate_cache_read (size_t len=((2) *1024 *1024), uint32_t numa_node=0)
bool free_cache_read ()
bool allocate_cache_write (size_t len=((2) *1024 *1024), uint32_t numa_node=0)
bool free_cache_write ()
bool allocate_cache_read_write (size_t len=((2) *1024 *1024), uint32_t numa_node=0)
bool free_cache_read_write ()
bool allocate_pinned_buffer (uint64_t **buf_ptr, size_t len=((2) *1024 *1024), uint32_t numa_node=0)
bool free_pinned_buffer (uint64_t *buf_ptr, size_t len=((2) *1024 *1024))
uint8_t * get_dsm () const
uint8_t * get_read () const
uint8_t * get_write () const
uint8_t * get_read_write () const
void set_mmap_access (he_mmap_access access=HE_CACHE_DMA_MMAP_RW)
Data Fields
std::shared_ptr< spdlog::logger > logger_
Protected Attributes
std::string name_
std::string afu_id_
CLI::App app_
std::string pci_addr_
std::string log_level_
uint32_t timeout_msec_
int fd_
uint8_t * mmio_base_
uint64_t mmio_len_
uint8_t * dsm_buffer_
uint64_t dsm_buf_len_
uint8_t * rd_buffer_
uint64_t rd_buf_len_
uint8_t * wr_buffer_
uint64_t wr_buf_len_
uint8_t * rd_wr_buffer_
uint64_t rd_wr_buf_len_
volatile uint64_t * wr_buffer_phy_addr_
struct dfl_cxl_cache_region_info rinfo_
std::string dev_path_ [2]
command::ptr_t current_command_
std::map< CLI::App *, command::ptr_t > commands_
he_mmap_access dma_mmap_access_
Detailed Description
Definition at line 266 of file he_cache_test.h.
Member Typedef Documentation
typedef int(* opae::afu_test::afu::command_fn) (afu *afu, CLI::App *app)
Definition at line 268 of file he_cache_test.h.
typedef int(* opae::afu_test::afu::command_fn) (afu *afu, CLI::App *app)
Definition at line 278 of file he_cache_test.h.
Member Enumeration Documentation
enum opae::afu_test::afu::exit_codes
Enumerator
success
not_run
not_found
no_access
exception
error
success
not_run
not_found
no_access
exception
error
Definition at line 269 of file he_cache_test.h.
enum opae::afu_test::afu::exit_codes
Enumerator
success
not_run
not_found
no_access
exception
error
success
not_run
not_found
no_access
exception
error
Definition at line 279 of file he_cache_test.h.
Constructor & Destructor Documentation
opae::afu_test::afu::afu (const char * name, const char * afu_id = nullptr, const char * log_level = nullptr) [inline]
Definition at line 278 of file he_cache_test.h.
References opae::afu_test::spdlog_levels().
virtual opae::afu_test::afu::~afu () [inline], [virtual]
Definition at line 298 of file he_cache_test.h.
opae::afu_test::afu::afu (const char * name, const char * afu_id = nullptr, const char * log_level = nullptr) [inline]
Definition at line 288 of file he_cache_test.h.
References opae::afu_test::spdlog_levels().
virtual opae::afu_test::afu::~afu () [inline], [virtual]
Definition at line 303 of file he_cache_test.h.
Member Function Documentation
CLI::App& opae::afu_test::afu::cli () [inline]
Definition at line 303 of file he_cache_test.h.
int opae::afu_test::afu::find_dev_feature () [inline]
Definition at line 305 of file he_cache_test.h.
References FEATURE_DEV, MAX_SIZE, and sysfs_read_u64().
void opae::afu_test::afu::unmap_mmio () [inline]
Definition at line 375 of file he_cache_test.h.
bool opae::afu_test::afu::map_mmio () [inline]
Definition at line 382 of file he_cache_test.h.
int opae::afu_test::afu::open_handle (const char * dev) [inline]
Definition at line 395 of file he_cache_test.h.
int opae::afu_test::afu::main (int argc, char * argv[]) [inline]
Definition at line 432 of file he_cache_test.h.
References app.
Referenced by main().
virtual int opae::afu_test::afu::run (CLI::App * app, command::ptr_t test) [inline], [virtual]
Reimplemented in mem_tg::mem_tg, host_exerciser::host_exerciser, dummy_afu::dummy_afu, cxl_mem_tg::cxl_mem_tg, host_exerciser::host_exerciser, and hello_fpga::hello_fpga.
Definition at line 474 of file he_cache_test.h.
References app.
Referenced by hello_fpga::hello_fpga::run(), host_exerciser::host_exerciser::run(), cxl_mem_tg::cxl_mem_tg::run(), dummy_afu::dummy_afu::run(), and mem_tg::mem_tg::run().
template<class T > CLI::App* opae::afu_test::afu::register_command () [inline]
Definition at line 498 of file he_cache_test.h.
Referenced by main().
uint64_t opae::afu_test::afu::read64 (uint32_t offset) [inline]
Definition at line 506 of file he_cache_test.h.
Referenced by mem_tg::tg_test::config_input_options(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), hello_fpga::he_cache_cmd::he_run_hello_fpga_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_ping_pong_test(), host_exerciser::he_cache_cmd::he_run_running_pointer_test(), host_exerciser::he_cmd::he_start_test(), hello_fpga::he_cmd::host_exerciser_errors(), host_exerciser::he_cmd::host_exerciser_errors(), host_exerciser::host_exerciser_cmd::host_exerciser_errors(), host_exerciser::host_exerciser_cmd::host_exerciser_status(), host_exerciser::host_exerciser_cmd::host_exerciser_swtestmsg(), hello_fpga::he_cmd::print_csr(), host_exerciser::he_cmd::print_csr(), hssi_100g_cmd::print_registers(), hssi_10g_cmd::print_registers(), hssi_200g_400g_cmd::print_registers(), host_exerciser::host_exerciser_cmd::run(), hssi_100g_cmd::run(), hssi_200g_400g_cmd::run(), mem_tg::tg_test::run(), mem_tg::tg_test::tg_perf(), and mem_tg::tg_test::tg_wait_test_completion().
void opae::afu_test::afu::write64 (uint32_t offset, uint64_t value) [inline]
Definition at line 511 of file he_cache_test.h.
Referenced by host_exerciser::he_cache_cmd::he_forcetestcmpl(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), hello_fpga::he_cache_cmd::he_run_hello_fpga_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_ping_pong_test(), host_exerciser::he_cache_cmd::he_run_running_pointer_test(), hello_fpga::he_cmd::he_start_test(), host_exerciser::he_cmd::he_start_test(), hello_fpga::he_cache_cmd::run(), host_exerciser::he_cache_cmd::run(), hssi_100g_cmd::run(), hssi_200g_400g_cmd::run(), host_exerciser::host_exerciser_cmd::run_single_test(), and hssi_100g_cmd::select_port().
uint32_t opae::afu_test::afu::read32 (uint32_t offset) [inline]
Definition at line 516 of file he_cache_test.h.
void opae::afu_test::afu::write32 (uint32_t offset, uint32_t value) [inline]
Definition at line 521 of file he_cache_test.h.
Referenced by mem_tg::tg_test::config_input_options(), host_exerciser::host_exerciser_cmd::he_forcetestcmpl(), mem_tg::tg_test::run_mem_test(), and host_exerciser::host_exerciser_cmd::run_single_test().
command::ptr_t opae::afu_test::afu::current_command () const [inline]
Definition at line 526 of file he_cache_test.h.
Referenced by sig_handler().
bool opae::afu_test::afu::allocate_dsm (size_t len = (( 4 )*1024), uint32_t numa_node = 0) [inline]
Definition at line 528 of file he_cache_test.h.
References buffer_allocate(), buffer_release(), and DFL_CXL_CACHE_DSM_BASE.
Referenced by host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), hello_fpga::he_cache_cmd::he_run_hello_fpga_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_ping_pong_test(), and host_exerciser::he_cache_cmd::he_run_running_pointer_test().
bool opae::afu_test::afu::free_dsm () [inline]
Definition at line 571 of file he_cache_test.h.
References buffer_release(), and DFL_CXL_CACHE_DSM_BASE.
Referenced by host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), hello_fpga::he_cache_cmd::he_run_hello_fpga_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_ping_pong_test(), host_exerciser::he_cache_cmd::he_run_running_pointer_test(), and hello_fpga::he_cache_cmd::hello_fpga_data_intg_check().
void opae::afu_test::afu::reset_dsm () [inline]
Definition at line 598 of file he_cache_test.h.
Referenced by host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), and host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test().
bool opae::afu_test::afu::allocate_cache_read (size_t len = (( 2 )*1024 * 1024), uint32_t numa_node = 0) [inline]
Definition at line 600 of file he_cache_test.h.
References buffer_allocate(), buffer_release(), DFL_CXL_CACHE_RD_ADDR_TABLE_DATA, and HE_CACHE_DMA_MMAP_RW.
Referenced by host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), and host_exerciser::he_cache_cmd::he_run_ping_pong_test().
bool opae::afu_test::afu::free_cache_read () [inline]
Definition at line 645 of file he_cache_test.h.
References buffer_release(), and DFL_CXL_CACHE_RD_ADDR_TABLE_DATA.
Referenced by host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), and host_exerciser::he_cache_cmd::he_run_ping_pong_test().
bool opae::afu_test::afu::allocate_cache_write (size_t len = (( 2 )*1024 * 1024), uint32_t numa_node = 0) [inline]
Definition at line 671 of file he_cache_test.h.
References buffer_allocate(), buffer_release(), DFL_CXL_CACHE_WR_ADDR_TABLE_DATA, and HE_CACHE_DMA_MMAP_RW.
Referenced by host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), and host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test().
bool opae::afu_test::afu::free_cache_write () [inline]
Definition at line 715 of file he_cache_test.h.
References buffer_release(), and DFL_CXL_CACHE_WR_ADDR_TABLE_DATA.
Referenced by host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_miss_test(), and host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test().
bool opae::afu_test::afu::allocate_cache_read_write (size_t len = (( 2 )*1024 * 1024), uint32_t numa_node = 0) [inline]
Definition at line 741 of file he_cache_test.h.
References buffer_allocate(), buffer_release(), DFL_CXL_CACHE_RD_ADDR_TABLE_DATA, DFL_CXL_CACHE_WR_ADDR_TABLE_DATA, and HE_CACHE_DMA_MMAP_RW.
Referenced by host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), and hello_fpga::he_cache_cmd::he_run_hello_fpga_test().
bool opae::afu_test::afu::free_cache_read_write () [inline]
Definition at line 792 of file he_cache_test.h.
References buffer_release(), DFL_CXL_CACHE_RD_ADDR_TABLE_DATA, and DFL_CXL_CACHE_WR_ADDR_TABLE_DATA.
Referenced by host_exerciser::he_cache_cmd::he_run_fpga_wr_cache_hit_test(), hello_fpga::he_cache_cmd::he_run_hello_fpga_test(), and hello_fpga::he_cache_cmd::hello_fpga_data_intg_check().
uint8_t* opae::afu_test::afu::get_dsm () const [inline]
Definition at line 825 of file he_cache_test.h.
Referenced by host_exerciser::he_cmd::get_penalty_start_ticks(), host_exerciser::he_cmd::get_ticks(), host_exerciser::he_cmd::he_get_perf(), hello_fpga::he_cmd::he_perf_counters(), host_exerciser::he_cmd::he_perf_counters(), host_exerciser::he_cmd::he_wait_test_completion(), and hello_fpga::he_cmd::he_wait_test_completion().
uint8_t* opae::afu_test::afu::get_read () const [inline]
Definition at line 827 of file he_cache_test.h.
Referenced by host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), and host_exerciser::he_cache_cmd::he_run_ping_pong_test().
uint8_t* opae::afu_test::afu::get_write () const [inline]
Definition at line 829 of file he_cache_test.h.
Referenced by host_exerciser::he_cache_cmd::he_run_host_wr_cache_hit_test().
uint8_t* opae::afu_test::afu::get_read_write () const [inline]
Definition at line 831 of file he_cache_test.h.
Referenced by hello_fpga::he_cache_cmd::he_run_hello_fpga_test().
void opae::afu_test::afu::set_mmap_access (he_mmap_access access = HE_CACHE_DMA_MMAP_RW) [inline]
Definition at line 833 of file he_cache_test.h.
Referenced by host_exerciser::he_cmd::he_set_bias_mode().
volatile uint64_t* opae::afu_test::afu::get_write_buff_phy_addr () const [inline]
Definition at line 836 of file he_cache_test.h.
Referenced by hello_fpga::he_cache_cmd::hello_fpga_data_intg_check().
CLI::App& opae::afu_test::afu::cli () [inline]
Definition at line 311 of file he_cache_test.h.
int opae::afu_test::afu::find_dev_feature () [inline]
Definition at line 313 of file he_cache_test.h.
References FEATURE_DEV, MAX_SIZE, and sysfs_read_u64().
void opae::afu_test::afu::unmap_mmio () [inline]
Definition at line 383 of file he_cache_test.h.
bool opae::afu_test::afu::map_mmio () [inline]
Definition at line 390 of file he_cache_test.h.
int opae::afu_test::afu::open_handle (const char * dev) [inline]
Definition at line 403 of file he_cache_test.h.
int opae::afu_test::afu::main (int argc, char * argv[]) [inline]
Definition at line 441 of file he_cache_test.h.
References app.
virtual int opae::afu_test::afu::run (CLI::App * app, command::ptr_t test) [inline], [virtual]
Reimplemented in mem_tg::mem_tg, host_exerciser::host_exerciser, dummy_afu::dummy_afu, cxl_mem_tg::cxl_mem_tg, host_exerciser::host_exerciser, and hello_fpga::hello_fpga.
Definition at line 485 of file he_cache_test.h.
References app.
template<class T > CLI::App* opae::afu_test::afu::register_command () [inline]
Definition at line 508 of file he_cache_test.h.
uint64_t opae::afu_test::afu::read64 (uint32_t offset) [inline]
Definition at line 516 of file he_cache_test.h.
void opae::afu_test::afu::write64 (uint32_t offset, uint64_t value) [inline]
Definition at line 521 of file he_cache_test.h.
uint32_t opae::afu_test::afu::read32 (uint32_t offset) [inline]
Definition at line 526 of file he_cache_test.h.
void opae::afu_test::afu::write32 (uint32_t offset, uint32_t value) [inline]
Definition at line 531 of file he_cache_test.h.
command::ptr_t opae::afu_test::afu::current_command () const [inline]
Definition at line 536 of file he_cache_test.h.
bool opae::afu_test::afu::allocate_dsm (size_t len = (( 4 )*1024), uint32_t numa_node = 0) [inline]
Definition at line 538 of file he_cache_test.h.
References buffer_allocate(), buffer_release(), and DFL_CXL_CACHE_DSM_BASE.
bool opae::afu_test::afu::free_dsm () [inline]
Definition at line 581 of file he_cache_test.h.
References buffer_release(), and DFL_CXL_CACHE_DSM_BASE.
void opae::afu_test::afu::reset_dsm () [inline]
Definition at line 609 of file he_cache_test.h.
bool opae::afu_test::afu::allocate_cache_read (size_t len = (( 2 )*1024 * 1024), uint32_t numa_node = 0) [inline]
Definition at line 614 of file he_cache_test.h.
References buffer_allocate(), buffer_release(), DFL_CXL_CACHE_RD_ADDR_TABLE_DATA, and HE_CACHE_DMA_MMAP_RW.
bool opae::afu_test::afu::free_cache_read () [inline]
Definition at line 658 of file he_cache_test.h.
References buffer_release(), and DFL_CXL_CACHE_RD_ADDR_TABLE_DATA.
bool opae::afu_test::afu::allocate_cache_write (size_t len = (( 2 )*1024 * 1024), uint32_t numa_node = 0) [inline]
Definition at line 685 of file he_cache_test.h.
References buffer_allocate(), buffer_release(), DFL_CXL_CACHE_WR_ADDR_TABLE_DATA, and HE_CACHE_DMA_MMAP_RW.
bool opae::afu_test::afu::free_cache_write () [inline]
Definition at line 728 of file he_cache_test.h.
References buffer_release(), and DFL_CXL_CACHE_WR_ADDR_TABLE_DATA.
bool opae::afu_test::afu::allocate_cache_read_write (size_t len = (( 2 )*1024 * 1024), uint32_t numa_node = 0) [inline]
Definition at line 755 of file he_cache_test.h.
References buffer_allocate(), buffer_release(), DFL_CXL_CACHE_RD_ADDR_TABLE_DATA, DFL_CXL_CACHE_WR_ADDR_TABLE_DATA, and HE_CACHE_DMA_MMAP_RW.
bool opae::afu_test::afu::free_cache_read_write () [inline]
Definition at line 804 of file he_cache_test.h.
References buffer_release(), DFL_CXL_CACHE_RD_ADDR_TABLE_DATA, and DFL_CXL_CACHE_WR_ADDR_TABLE_DATA.
bool opae::afu_test::afu::allocate_pinned_buffer (uint64_t ** buf_ptr, size_t len = (( 2 )*1024 * 1024), uint32_t numa_node = 0) [inline]
Definition at line 839 of file he_cache_test.h.
References buffer_allocate(), and buffer_release().
Referenced by host_exerciser::he_cache_cmd::he_run_running_pointer_test().
bool opae::afu_test::afu::free_pinned_buffer (uint64_t * buf_ptr, size_t len = (( 2 )*1024 * 1024)) [inline]
Definition at line 877 of file he_cache_test.h.
References buffer_release().
Referenced by host_exerciser::he_cache_cmd::he_run_running_pointer_test().
uint8_t* opae::afu_test::afu::get_dsm () const [inline]
Definition at line 905 of file he_cache_test.h.
uint8_t* opae::afu_test::afu::get_read () const [inline]
Definition at line 907 of file he_cache_test.h.
uint8_t* opae::afu_test::afu::get_write () const [inline]
Definition at line 909 of file he_cache_test.h.
uint8_t* opae::afu_test::afu::get_read_write () const [inline]
Definition at line 911 of file he_cache_test.h.
void opae::afu_test::afu::set_mmap_access (he_mmap_access access = HE_CACHE_DMA_MMAP_RW) [inline]
Definition at line 913 of file he_cache_test.h.
Field Documentation
std::string opae::afu_test::afu::name_ [protected]
Definition at line 841 of file he_cache_test.h.
Referenced by mem_tg::mem_tg::duplicate().
std::string opae::afu_test::afu::afu_id_ [protected]
Definition at line 842 of file he_cache_test.h.
Referenced by mem_tg::mem_tg::duplicate().
CLI::App opae::afu_test::afu::app_ [protected]
Definition at line 843 of file he_cache_test.h.
std::string opae::afu_test::afu::pci_addr_ [protected]
Definition at line 844 of file he_cache_test.h.
Referenced by mem_tg::mem_tg::duplicate().
std::string opae::afu_test::afu::log_level_ [protected]
Definition at line 845 of file he_cache_test.h.
Referenced by mem_tg::mem_tg::duplicate().
uint32_t opae::afu_test::afu::timeout_msec_ [protected]
Definition at line 846 of file he_cache_test.h.
Referenced by mem_tg::mem_tg::duplicate().
int opae::afu_test::afu::fd_ [protected]
Definition at line 848 of file he_cache_test.h.
uint8_t * opae::afu_test::afu::mmio_base_ [protected]
Definition at line 849 of file he_cache_test.h.
uint64_t opae::afu_test::afu::mmio_len_ [protected]
Definition at line 850 of file he_cache_test.h.
uint8_t * opae::afu_test::afu::dsm_buffer_ [protected]
Definition at line 852 of file he_cache_test.h.
uint64_t opae::afu_test::afu::dsm_buf_len_ [protected]
Definition at line 853 of file he_cache_test.h.
uint8_t * opae::afu_test::afu::rd_buffer_ [protected]
Definition at line 855 of file he_cache_test.h.
uint64_t opae::afu_test::afu::rd_buf_len_ [protected]
Definition at line 856 of file he_cache_test.h.
uint8_t * opae::afu_test::afu::wr_buffer_ [protected]
Definition at line 858 of file he_cache_test.h.
uint64_t opae::afu_test::afu::wr_buf_len_ [protected]
Definition at line 859 of file he_cache_test.h.
uint8_t * opae::afu_test::afu::rd_wr_buffer_ [protected]
Definition at line 861 of file he_cache_test.h.
uint64_t opae::afu_test::afu::rd_wr_buf_len_ [protected]
Definition at line 862 of file he_cache_test.h.
volatile uint64_t* opae::afu_test::afu::wr_buffer_phy_addr_ [protected]
Definition at line 864 of file he_cache_test.h.
struct dfl_cxl_cache_region_info opae::afu_test::afu::rinfo_ [protected]
Definition at line 864 of file he_cache_test.h.
std::string opae::afu_test::afu::dev_path_ [protected]
Definition at line 868 of file he_cache_test.h.
command::ptr_t opae::afu_test::afu::current_command_ [protected]
Definition at line 870 of file he_cache_test.h.
std::map< CLI::App *, command::ptr_t > opae::afu_test::afu::commands_ [protected]
Definition at line 871 of file he_cache_test.h.
he_mmap_access opae::afu_test::afu::dma_mmap_access_ [protected]
Definition at line 873 of file he_cache_test.h.
std::shared_ptr< spdlog::logger > opae::afu_test::afu::logger_
Definition at line 876 of file he_cache_test.h.
Referenced by host_exerciser::he_cmd::create_linked_list(), mem_tg::mem_tg::duplicate(), host_exerciser::he_cache_cmd::he_continuousmode(), host_exerciser::host_exerciser_cmd::he_continuousmode(), host_exerciser::host_exerciser_cmd::he_perf_counters(), hello_fpga::he_cmd::he_perf_counters(), host_exerciser::he_cmd::he_perf_counters(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_fpga_rd_cache_miss_test(), host_exerciser::he_cache_cmd::he_run_host_rd_cache_hit_test(), host_exerciser::he_cache_cmd::he_run_ping_pong_test(), host_exerciser::he_cache_cmd::he_run_running_pointer_test(), host_exerciser::he_cmd::he_start_test(), host_exerciser::host_exerciser_cmd::host_exerciser_status(), hello_fpga::he_cmd::print_csr(), host_exerciser::he_cmd::print_csr(), host_exerciser::he_cmd::print_linked_list(), host_exerciser::host_exerciser_cmd::run(), mem_tg::tg_test::run_mem_test(), host_exerciser::host_exerciser_cmd::run_single_test(), and host_exerciser::he_cmd::verify_linked_list().
Author
Generated automatically by Doxygen for OPAE C API from the source code.